### ISSUE TITLE
Multiple warnings when on a Portuguese version

### ISSUE THREAD

**Issue by gustavo-hms** [Aerilius/sketchup-console-plus#22]
If Sketchup is translated to Portuguese, multiple warnings are shown every time I type in the console, like this one:

```
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/Users/[...]/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
```

**Comment by Aerilius** [comment]
The warnings should help detect missing translation strings (when a translation for that language is available but not complete). But since I don't have a Portuguese translation, it should fallback and load English which is complete and should not cause warnings.

**Comment by Aerilius** [comment]
This should be fixed with commit fa6b2b05e8b236f8239e4ae13a74e1f1bf5608e6.

**Comment by gustavo-hms** [comment]
Sorry for not replying it before: I didn't have the opportunity to test it until now. Nevertheless, I'm not being able to build the extension. When I follow the instructions on README, typing `bundle exec rake --tasks build`, I get the following errors:

```
rake aborted!
Unable to determine name from existing gemspec. Use :name => 'gemname' in #install_tasks to manually set it.
/[...]/sketchup-console-plus/Rakefile:1:in `<top (required)>'
/bin/bundle:23:in `load'
/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

Am I supposed to do something before it?

Thanks in advance

**Comment by Aerilius** [comment]
Sorry, the gemspec file was missing from the repository.

You don't need to build the extension in order to use it, you can just symlink (or copy) the contents of the `src` directory into your plugins folder (`ae_console.rb` and `ae_console/`). The release page has also an .rbz for 3.0.3 which contains the above fix.

**Comment by gustavo-hms** [comment]
> You don't need to build the extension in order to use it, you can just symlink (or copy) the contents of the src directory into your plugins folder (ae_console.rb and ae_console/). 

Hmm... I should know it. Thanks, and sorry for the inconvenience.

> The release page has also an .rbz for 3.0.3 which contains the above fix.

If version 3.0.3 already contains the fix, then there are still some problems remaining. Here's the console output when it tries to complete a single command I type (the output has probably been clipped due to history size limitations, since the console hangs for about a second) 

```
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/translate.rb:38:in `warn'
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/translate.rb:38:in `get'
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/feature_autocomplete.rb:41:in `block in autocomplete_token_list'
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/feature_autocomplete.rb:36:in `map!'
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/feature_autocomplete.rb:36:in `autocomplete_token_list'
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/feature_autocomplete.rb:16:in `block (2 levels) in initialize'
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/bridge.rb:286:in `call'
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/bridge.rb:286:in `__request_handler_htmldialog__'
SketchUp:1:in `call'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Ruby Console operatio"... not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/feature_wrap_in_undo.rb:23:in `block in initialize_console'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
warning: key "Parameters" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:78:in `get_documentation_html'
warning: key "Return value" not found for locale pt-BR (AE::ConsolePlugin::Translate)
C:/users/gustavo/Application Data/SketchUp/SketchUp 2017/SketchUp/Plugins/ae_console/features/docprovider.rb:91:in `get_documentation_html'
```

**Comment by Aerilius** [comment]
Can you try it again from master (with commit 21ca438b9c4a067f691ce3e9db8728362c491106)

**Comment by gustavo-hms** [comment]
Sure. I've tested it, but the issue still persists, even with the above commit.
